#!/usr/bin/env python3
import sys
import re

if len(sys.argv)<2:
    print("Usage: ./clean-data <data>")
    sys.exit()

file=open("data/%s.txt"%sys.argv[1],"r")
data=[]

for line in file:
    line=line.rstrip().lower()
    if line in data: continue
    m=re.match("^[A-Za-z]+$",line)
    if m: data.append(line)
file.close()

file=open("data/%s.txt"%sys.argv[1],"w")
for d in data:
    file.write("%s\n"%d)
file.close()
print("All done")
